CHANGELOG.md, README.md
He creado las siguientes carpetas:
=> [PR1] DEV-5 Create root structure and src directories

src/Shared/PacketAdapter/PacketAdapter.go
Esta clase ofrece dos funciones, una para enviar ordener y otra para recibir paquetes. La primera la usará OrderTransfer y la segunda la usará DataTransfer
=> [PR1] DEV-7 Added Packet Adapter

src/DataTransfer/application/data_transfer.go, src/Shared/PacketAdapter/application/packet_adapter.go, src/cmd/MVP-1/main.go
Small change so DataTransfer outputs packages through a channel. Both the logger and the DataWebSocket will use the packets outputed by this channel.
=> [PR1] DEV-18 Added channel to DataTranfer

src/DataTransfer/application/create_log_file.go, src/DataTransfer/application/data_transfer.go, src/cmd/MVP-1/main.go
It creates a file that overwrites the previous run, from each package it prints the props we are interested in, as well as each measurement.
=> [PR1] DEV-12: MVP-1 logger

src/Shared/Logger/infra/log.go, src/Shared/Logger/infra/value_timestamp.go
This PR adds the logger to the code base. I think it's done, but pls let me know if there is something missing
=> [PR1] DEV-14 added logger

src/DataTransfer/application/data_transfer.go, src/cmd/MVP-1/Logger/logger.go, src/cmd/MVP-1/main.go
Now the logger recieves the packets from a channel
=> [PR1] DEV-20 Integrated MVP-1 logger with new DataTransfer

src/OrderTransfer/domain/order.go, src/OrderTransfer/order_transfer.go, src/OrderTransfer/order_web_adapter.go
Added OrderTransfer, which sends orders receive in a WS to the boards. The OrderWebAdapter has to be moved to the server/web_adapters folder once its available.
=> [PR1] DEV-17 Added OrderTransfer

src/MessageTransfer/message_transfer.go, src/Shared/StreamingHandlers/streaming.go, src/Shared/StreamingHandlers/web_adapters.go
Added message transfer to differentiate from the other data that must be sent to the front
=> [PR1] DEV-26 add message transfer

src/Shared/Server/infra/http.go, src/Shared/Server/infra/log.go, src/Shared/Server/infra/server_test.go, src/Shared/Server/infra/spa.go, src/Shared/Server/infra/test/resources/index.html, src/Shared/Server/infra/test/resources/index.js
This PR adds test for the Server module.
=> [PR1] DEV-47 add Server tests

src/Shared/Server/domain/board.go, src/Shared/Server/domain/measurement.go, src/Shared/Server/domain/packet.go, src/Shared/Server/domain/pod_data.go, src/Shared/Server/infra/mappers/board.go, src/Shared/Server/infra/mappers/measurement.go, src/Shared/Server/infra/mappers/packet.go, src/Shared/Server/infra/mappers/pod_data.go, src/Shared/Server/infra/pod_data.go
This PR adds the PodData struct to the Server that is sent to the front when connecting
=> [PR1] DEV-51 add PodData to Server

src/connection_transfer/connection_transfer.go, src/data_transfer/data_transfer.go, src/message_transfer/message_transfer.go, src/order_transfer/order_transfer.go, src/transport_controller/internals/pipe_handle.go, src/transport_controller/transport_controller.go
Previous websocket implementation was flawed, these changes should fix most of those problems. It also adds some methods to make later integration easier
=> [PR1] DEV-82 improve websocket interfaces

README.md
This is a very basic README for our repo so people checking it for the first time have some idea about it and its authors
=> [PR1] DEV-32 Add README

src/go.mod, src/go.sum, src/main.go
The new interface prompts the user for the interface they want to use for the sniffer. It is a list of all the detected interfaces with their name, description and addresses. Then the users enters the index of the list they want to use.
Once the interface is selected, the execution continues as before
=> [PR 1] DEV-157 interface input selection

src/config.toml, src/main.go, src/message_logger/loggable_info.go, src/message_logger/loggable_protection.go, src/message_logger/message_logger.go, src/vehicle/config.go, src/vehicle/constructor.go, src/vehicle/message_parser/constructor.go, src/vehicle/message_parser/message_adapter.go, src/vehicle/message_parser/message_parser.go, src/vehicle/models/messages.go, src/vehicle/models/time_accumulation.go, src/vehicle/vehicle.go
This adds the deconding and logging of the info messaeg to the backend.
=> [PR 1] DEV-175 Added info message backend

.gitignore, src/blcu/blcu.go, src/blcu/download.go, src/blcu/upload.go, src/common/numbers.go, src/config.toml, src/vehicle/models/order_data.go
After integrating the BLCU logic with FW, here are the fixes necessary to make it work, it also features an update to notify the progress to the frontend. However, This is currently not supported by the frontend and will cause issues.
=> [PR 1] DEV-177 BLCU fixes

src/config.toml, src/main.go, src/server/handler.go, src/server/server.go, src/server/websocket.go, src/websocket_broker/models/handler.go, src/websocket_broker/ws_handle.go
Now the websocket handler doesn't distinguish between server, it stores all websocket connections in the same map. Additionaly, the closer handler from the connections substract one to the server connection count.
=> [PR 1] DEV-180 Simplified websocket handler.

.github/workflows/pre-release.yaml, .github/workflows/release.yaml
Previous actions were running on an unexisting target, this runs on ubuntu-latest
=> [PR 2] DEV-189 change runs-on distro

.github/workflows/pre-release.yaml, .github/workflows/release.yaml
I forgot to change the dependency installation command, this fixes it.
=> [PR 3] DEV-189 fix installation command

.github/workflows/pre-release.yaml, .github/workflows/release.yaml
Ok, I hope THIS is the last change TT.
=> [PR 1] DEV-189 move working directory

.github/workflows/pre-release.yaml, .github/workflows/release.yaml
=> [PR 6] DEV-189 fix secret path

.github/workflows/pre-release.yaml, .github/workflows/release.yaml
Change the environment of the workflow to alpine linux, which should work
=> [PR 7] DEV-189 run in alpine linux

.github/workflows/pre-release.yaml, .github/workflows/release.yaml
Forgot to use the correct shell
=> [PR 8] DEV-189 change to alpine shell
